requirements.txt: fix django-crispy-form version to workaround upstream bug
On my local instance, accessing http://localhost:8000/membres/inscription
fails with error:
  'Settings' object has no attribute 'CRISPY_TEMPLATE_PACK'

According to the link below
  https://github.com/maraujop/django-crispy-forms/issues/237
This is due to a bug with recent versions of django-crispy-form
(pip installs 1.4.0 by default on my machine). As advised on the
bugtracker, pinning the version to 1.3.2 makes the issue go away.